<?php

namespace WordsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CheckResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckResultRepository extends EntityRepository
{
}
