<?php

namespace WordsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnusedWordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnusedWordsRepository extends EntityRepository
{
}
