<?php

namespace WordsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordsRepository extends EntityRepository
{
}
