<?php

namespace WordsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WordsResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordsResultRepository extends EntityRepository
{
}
