<?php

namespace WordsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WordsFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordsFilesRepository extends EntityRepository
{
}
