<?php

namespace GoodsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GoodsFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsFilesRepository extends EntityRepository
{
}
