<?php

namespace GoodsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShopModelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopModelsRepository extends EntityRepository
{
}
