<?php

namespace GoodsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StyleTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StyleTypesRepository extends EntityRepository
{
}
