<?php

namespace ShelfBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShelfUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShelfUsersRepository extends EntityRepository
{
}
