<?php

namespace ShelfBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShopsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopsRepository extends EntityRepository
{
}
