# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                default_target_path: /profile
            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # A week
                path:     /

    access_control:
        - { path: ^/login$,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile$,      role: ROLE_USER } # The all user account
        - { path: ^/profile/admin, role: ROLE_SUPER_ADMIN } # The administrator account
        - { path: ^/profile/user,  role: ROLE_GENERAL } # The general account
        - { path: ^/shelf,         role: ROLE_SHELF } # The shelf account
        - { path: ^/words,         role: ROLE_WORDS } # The unused words account
        - { path: ^/michelin,      role: ROLE_MICHELIN } # The michelin store account

#    role_hierarchy:
#        ROLE_ADMIN: ROLE_SUPER_ADMIN
