# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # A week
                path:     /

    access_control:
        - { path: ^/login$,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile,   role: ROLE_USER }
        - { path: ^/admin,     role: ROLE_ADMIN }
        - { path: ^/words,     role: ROLE_WORDS }
        - { path: ^/goods,     role: ROLE_GOODS }

    role_hierarchy:
        ROLE_USER:  ROLE_USER
        ROLE_ADMIN: ROLE_SUPER_ADMIN
        ROLE_WORDS: [ROLE_WORDS, ROLE_USER, ROLE_SUPER_ADMIN]
        ROLE_GOODS: [ROLE_GOODS, ROLE_USER, ROLE_SUPER_ADMIN]
