# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # Knp-Menu-Bundle
    app.menu_builder:
        class: PublicBundle\Menu\MenuBuilder
        arguments: [@knp_menu.factory, @doctrine]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar }

    # FileUtil
    FileUtilService:
        class: PublicBundle\Services\FileUtilService

    #UploadHandle
    UploadHandlerService:
        class: PublicBundle\Services\UploadHandlerService

    GetMessageService:
        class: PublicBundle\Services\GetMessageService
