<?php

namespace MichelinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MichelinCitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MichelinCitiesRepository extends EntityRepository
{
}
