<?php

namespace MichelinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MichelinStoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MichelinStoresRepository extends EntityRepository
{
}
