<?php

namespace PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AreasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreasRepository extends EntityRepository
{
}
