<?php

namespace PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UploadFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadFilesRepository extends EntityRepository
{
    /**
     * Query the user is not deleted file
     *
     * @param Entity $user
     * @param string $type
     * @return mixed
     */
    public function findByUserNotDel($user, $type)
    {
        $fileInfo = $this->findBy(array('user' => $user, 'del' => false, 'type' => $type));
        return $fileInfo;
    }
}
