<?php

namespace UsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    /**
     * Find current shop
     *
     * @param Entity $user
     * @return mixed
     */
    public function findCurrentShop($user)
    {
        return $this->_em->createQuery("
              SELECT s FROM ShelfBundle:Shops AS s JOIN ShelfBundle:ShelfUsers AS u WITH s.plat = u.plat AND s.brand = u.brand WHERE u.user = :user"
        )->setParameter("user", $user)->getSingleResult();
    }
}
